[package]
name = "throttler"
version = "0.1.0"
authors = ["Symphorien Gibol <symphorien@xlumurb.eu>"]

[dependencies]
procure = "*"
procinfo = "0.2.2"
glob = "*"
time = "*"
libc = "*"
nix = "*"
sysconf = "*"
